# Generated by Django 4.1.4 on 2023-01-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_author_book_autor_rename_pdf_book_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='documentos/docs/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='documentos/portadas/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
