# Generated by Django 4.1.4 on 2023-01-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documento_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='portada',
        ),
    ]
