# Generated by Django 4.1.4 on 2023-01-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documento_url_accesible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='url_accesible',
            new_name='nombre_accesible',
        ),
    ]
