# Generated by Django 4.1.4 on 2023-01-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_url_accesible_documento_nombre_accesible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='nombre_accesible',
        ),
    ]
