# Generated by Django 4.1.4 on 2023-01-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_documento_nombre_accesible'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nombre_accesible',
            field=models.CharField(default='', max_length=100),
        ),
    ]
